# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5884665284eb7b77acc5004b94642b4123da8383d5726fc1e60c3078767680270c18068d23e9dc8f6bc8c05c1a4e0d6fd24ec84ff65ee007269c2adfa32d245

test:
  secret_key_base: ed2864fd6cdc365f581d3b68cbf66324a41dc84c6ef6f7d7fd0710ace225da6c8f4fece20d9a48a15edb4d6b14a00482141c67c6dfef5d621f49e2ee6c71752b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
